spring:
  application:
    name: security_app_backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

groq:
  api:
    key: ${GROQ_API_KEY}
    base-url: https://api.groq.com/openai/v1
  models:
    text: ${GROQ_MODEL_TEXT}
    vision: ${GROQ_MODEL_VISION}
    audio: ${GROQ_MODEL_AUDIO}
